replicaCount: 2

image:
  repository: replace-me.dkr.ecr.eu-central-1.amazonaws.com/rentacar-api
  tag: latest
  pullPolicy: IfNotPresent

environment: Production

connectionString:
  existingSecret: rentacar-api-secrets
  key: DefaultConnection

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: rentacar.example.com
      paths:
        - path: /
          pathType: Prefix

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
