apiVersion: v1
kind: Namespace
metadata:
  name: rentacar-production
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: rentacar-api
    deployment.environment: production
