image:
  repository: REPLACE_WITH_ECR_REPOSITORY
  tag: REPLACE_WITH_COMMIT_SHA
  digest: ""

gitops:
  commitSha: REPLACE_WITH_COMMIT_SHA

deploymentMetadata:
  promotedFrom: staging
  approvedBy: REPLACE_WITH_APPROVER
  workflowRunUrl: ""
