apiVersion: v1
kind: Secret
metadata:
  name: rentacar-api-secrets
  namespace: rentacar
type: Opaque
stringData:
  DefaultConnection: "Host=<rds-endpoint>;Port=5432;Database=rentacardb;Username=rentacar;Password=<db-password>"
